#include "compatibility.m"
int main(){@autoreleasepool{
 id<MTLDevice>d=MTLCreateSystemDefaultDevice();NSError*err=nil;
 NSString*ms=@"#include <metal_stdlib>\nusing namespace metal;struct V{float4 p[[position]];};[[mesh]] void auditMesh(mesh<V,void,3,1,topology::triangle> m){m.set_vertex(0,V{float4(-1,-1,0,1)});m.set_vertex(1,V{float4(3,-1,0,1)});m.set_vertex(2,V{float4(-1,3,0,1)});m.set_index(0,0);m.set_index(1,1);m.set_index(2,2);m.set_primitive_count(1);}fragment float4 auditFS(){return float4(1,0,0,0.5);}";
 id<MTLLibrary>ml=[d newLibraryWithSource:ms options:nil error:&err];if(!ml){NSLog(@"%@",err);return 11;}MTLMeshRenderPipelineDescriptor*md=[MTLMeshRenderPipelineDescriptor new];md.meshFunction=[ml newFunctionWithName:@"auditMesh"];md.fragmentFunction=[ml newFunctionWithName:@"auditFS"];md.colorAttachments[0].pixelFormat=0;unsigned char ownerBytes[0x400]={0};uint64_t stack[16]={0};stack[5]=(uintptr_t)ownerBytes;ownerBytes[0x70+0x255]=1;unsigned char color[12]={1,0,4,5,0,1,0,0,4,15,0,0};memcpy(ownerBytes+0x70+0x258,color,12);objc_setAssociatedObject(md.colorAttachments,&sourceStateKey,sourceDecode((uintptr_t)stack),OBJC_ASSOCIATION_RETAIN_NONATOMIC);id mp=[d newRenderPipelineStateWithMeshDescriptor:md options:0 reflection:nil error:&err];if(!mp||![objc_getAssociatedObject(mp,&writerPipelineKey)[@"mesh"] isEqual:@"auditMesh"]){NSLog(@"%@",err);return 12;}
 MTLTextureDescriptor*mt=[MTLTextureDescriptor texture2DDescriptorWithPixelFormat:70 width:16 height:16 mipmapped:NO];mt.storageMode=MTLStorageModeShared;mt.usage=MTLTextureUsageRenderTarget;id<MTLTexture>tex=[d newTextureWithDescriptor:mt];id<MTLCommandBuffer>mcb=[[d newCommandQueue] commandBuffer];MTLRenderPassDescriptor*mr=[MTLRenderPassDescriptor renderPassDescriptor];mr.colorAttachments[0].texture=tex;mr.colorAttachments[0].loadAction=MTLLoadActionClear;mr.colorAttachments[0].storeAction=MTLStoreActionStore;id<MTLRenderCommandEncoder>me=[mcb renderCommandEncoderWithDescriptor:mr];[me setRenderPipelineState:mp];[me drawMeshThreadgroups:MTLSizeMake(1,1,1) threadsPerObjectThreadgroup:MTLSizeMake(1,1,1) threadsPerMeshThreadgroup:MTLSizeMake(1,1,1)];[me drawMeshThreadgroups:MTLSizeMake(1,1,1) threadsPerObjectThreadgroup:MTLSizeMake(1,1,1) threadsPerMeshThreadgroup:MTLSizeMake(1,1,1)];[me endEncoding];[mcb commit];[mcb waitUntilCompleted];unsigned char px[1024];[tex getBytes:px bytesPerRow:64 fromRegion:MTLRegionMake2D(0,0,16,16) mipmapLevel:0];if(mcb.status!=MTLCommandBufferStatusCompleted||sourceRepairs!=1)return 13;for(int i=0;i<256;i++)if(px[i*4]<190||px[i*4]>193||px[i*4+1]||px[i*4+2]||px[i*4+3]<127||px[i*4+3]>128)return 14;puts("PASS: mesh original-state restoration, 256 pixels correct two-layer alpha blend, completed");
 NSString*src=@"#include <metal_stdlib>\nusing namespace metal;vertex float4 writerVS(uint i[[vertex_id]]){float2 a[3]={float2(-1,-1),float2(3,-1),float2(-1,3)};return float4(a[i],0,1);}fragment float4 writerFS(){return float4(1,0,0,1);}";
 id<MTLLibrary>l=[d newLibraryWithSource:src options:nil error:&err];MTLRenderPipelineDescriptor*pd=[MTLRenderPipelineDescriptor new];pd.vertexFunction=[l newFunctionWithName:@"writerVS"];pd.fragmentFunction=[l newFunctionWithName:@"writerFS"];pd.colorAttachments[0].pixelFormat=0;id ps=[d newRenderPipelineStateWithDescriptor:pd error:&err];if(!ps)return 2;
 MTLTextureDescriptor*td=[MTLTextureDescriptor texture2DDescriptorWithPixelFormat:70 width:16 height:16 mipmapped:NO];td.storageMode=MTLStorageModeShared;td.usage=MTLTextureUsageRenderTarget|MTLTextureUsageShaderRead|MTLTextureUsagePixelFormatView;id<MTLTexture>t=[d newTextureWithDescriptor:td];id<MTLTexture>view=[t newTextureViewWithPixelFormat:70];id<MTLCommandQueue>q=[d newCommandQueue];id<MTLCommandBuffer>cb=[q commandBuffer];MTLRenderPassDescriptor*rp=[MTLRenderPassDescriptor renderPassDescriptor];rp.colorAttachments[0].texture=view;rp.colorAttachments[0].loadAction=MTLLoadActionClear;rp.colorAttachments[0].storeAction=MTLStoreActionStore;id<MTLRenderCommandEncoder>e=[cb renderCommandEncoderWithDescriptor:rp];[e setRenderPipelineState:ps];MTLDepthStencilDescriptor*dd=[MTLDepthStencilDescriptor new];dd.depthCompareFunction=MTLCompareFunctionAlways;id ds=[d newDepthStencilStateWithDescriptor:dd];[e setDepthStencilState:ds];[e setScissorRect:(MTLScissorRect){0,0,16,16}];[e setViewport:(MTLViewport){0,0,16,16,0,1}];[e drawPrimitives:MTLPrimitiveTypeTriangle vertexStart:0 vertexCount:3];[e endEncoding];[cb commit];[cb waitUntilCompleted];
 puts("PASS: standard raster fallback also renders256red pixels.");return 0;
}}
